[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
